### ISSUE TITLE
Time-zone issue after posting article

### ISSUE THREAD

**Issue by komica-random-person** [komica-random-person/HorrificIsland#12]
Should use GMT+8 for all time-zone.

**Comment by komician** [comment]
Please also remove this:
https://github.com/komica-random-person/HorrificIsland/blob/6122586ee390eb723fdc1881a414ee663f88135f/server.js#L10
This is the most shit way to set environment variable. Please consider:
1. Setting the variable on your *heroku* machine
2. In `pm2` or `forever` set the environment
3. If u run the server with command line, `TZ=Asia/Taipei yarn <start-server-script>`
